-- Upsert a chunk slice row while preserving deterministic ordering metadata.
INSERT INTO chunk_slices (
    batch_id,
    file_id,
    symbol_id,
    parent_symbol_id,
    chunk_id,
    handler_name,
    handler_version,
    part_index,
    part_total,
    start_line,
    end_line,
    start_byte,
    end_byte,
    token_count,
    content_hash,
    content_norm_hash,
    content_text,
    overflow_is_truncated,
    overflow_reason,
    metadata_json,
    created_at,
    updated_at,
    first_seen_batch,
    last_seen_batch
)
VALUES (
    :batch_id,
    :file_id,
    :symbol_id,
    :parent_symbol_id,
    :chunk_id,
    :handler_name,
    :handler_version,
    :part_index,
    :part_total,
    :start_line,
    :end_line,
    :start_byte,
    :end_byte,
    :token_count,
    :content_hash,
    :content_norm_hash,
    :content_text,
    :overflow_is_truncated,
    :overflow_reason,
    :metadata_json,
    :created_at,
    :updated_at,
    :first_seen_batch,
    :last_seen_batch
)
ON CONFLICT(batch_id, chunk_id, part_index)
DO UPDATE SET
    symbol_id = excluded.symbol_id,
    parent_symbol_id = excluded.parent_symbol_id,
    handler_name = excluded.handler_name,
    handler_version = excluded.handler_version,
    part_total = excluded.part_total,
    start_line = excluded.start_line,
    end_line = excluded.end_line,
    start_byte = excluded.start_byte,
    end_byte = excluded.end_byte,
    token_count = excluded.token_count,
    content_hash = excluded.content_hash,
    content_norm_hash = excluded.content_norm_hash,
    content_text = excluded.content_text,
    overflow_is_truncated = excluded.overflow_is_truncated,
    overflow_reason = excluded.overflow_reason,
    metadata_json = excluded.metadata_json,
    updated_at = excluded.updated_at,
    last_seen_batch = excluded.last_seen_batch;
