"""Vector database (VDB) module primitives."""

from __future__ import annotations

from .faiss_index import (
    FaissIndex,
    FaissIndexError,
    FaissIndexLoadError,
    FaissIndexLockError,
    FaissIndexLockTimeoutError,
    FaissIndexMetric,
    FaissIndexValidationError,
    FaissIndexPersistenceError,
    FaissIndexRemoveError,
    FaissIndexSidecar,
    index_lock_path,
    index_writer_lock,
    load_index_artifacts,
    persist_index_artifacts,
    sidecar_path_for_index,
)
from .models import (
    EmbeddingModel,
    Vdb,
    VdbHealthEntry,
    VdbInfoCounts,
    VdbInfoSummary,
)
from .providers import (
    EmbedRequestOptions,
    EmbeddingMatrix,
    EmbeddingProviderCaps,
    EmbeddingProviderModel,
    EmbeddingVector,
    EmbeddingsProvider,
    ProviderFactory,
    ProviderInitContext,
    ProviderNotRegisteredError,
    ProviderRegistry,
    ProviderRegistryError,
    resolve_sync_concurrency,
)
from .service import (
    VdbCreateError,
    VdbInfoError,
    VdbResetError,
    VdbService,
    VdbServiceError,
    VdbSyncError,
)

__all__ = [
    "FaissIndex",
    "FaissIndexError",
    "FaissIndexLoadError",
    "FaissIndexLockError",
    "FaissIndexLockTimeoutError",
    "FaissIndexMetric",
    "FaissIndexValidationError",
    "FaissIndexPersistenceError",
    "FaissIndexRemoveError",
    "FaissIndexSidecar",
    "index_lock_path",
    "index_writer_lock",
    "load_index_artifacts",
    "persist_index_artifacts",
    "sidecar_path_for_index",
    "EmbeddingModel",
    "Vdb",
    "VdbHealthEntry",
    "VdbInfoCounts",
    "VdbInfoSummary",
    "EmbedRequestOptions",
    "EmbeddingMatrix",
    "EmbeddingProviderCaps",
    "EmbeddingProviderModel",
    "EmbeddingVector",
    "EmbeddingsProvider",
    "ProviderFactory",
    "ProviderInitContext",
    "ProviderNotRegisteredError",
    "ProviderRegistry",
    "ProviderRegistryError",
    "resolve_sync_concurrency",
    "VdbService",
    "VdbServiceError",
    "VdbCreateError",
    "VdbSyncError",
    "VdbInfoError",
    "VdbResetError",
]
