# Default configuration bundled with raggd
# Generated workspaces copy this file alongside the rendered raggd.toml so you
# can inspect baseline settings and module toggles.

workspace = "~/.raggd"
log_level = "INFO"

[db]
manifest_modules_key = "modules"
manifest_db_module_key = "db"
manifest_backup_retention = 5
manifest_lock_timeout = 5.0
manifest_lock_poll_interval = 0.1
manifest_lock_suffix = ".lock"
manifest_backup_suffix = ".bak"
manifest_strict = true
manifest_backups_enabled = true
migrations_path = "resources/db/migrations"
ensure_auto_upgrade = true
vacuum_max_stale_days = 7
vacuum_concurrency = "auto"
run_allow_outside = true
run_autocommit_default = false
drift_warning_seconds = 0

[modules]

[modules.source]
enabled = true
extras = []

[modules.db]
enabled = true
extras = ["db"]

[modules.file-monitoring]
enabled = false
extras = ["file-monitoring"]

[modules.local-embeddings]
enabled = false
extras = ["local-embeddings"]

[modules.mcp]
enabled = false
extras = ["mcp"]

[modules.mcp-rest]
enabled = false
extras = ["mcp-rest"]

[modules.parser]
enabled = true
extras = ["parser"]
general_max_tokens = 2000
max_concurrency = "auto"
fail_fast = false
gitignore_behavior = "combined"
# Database lock telemetry thresholds drive parser health alerts.
lock_wait_warning_seconds = 5.0
lock_wait_error_seconds = 30.0
lock_contention_warning = 3
lock_contention_error = 10

[modules.parser.handlers]

[modules.parser.handlers.text]
enabled = true

[modules.parser.handlers.markdown]
enabled = true

[modules.parser.handlers.python]
enabled = true

[modules.parser.handlers.javascript]
enabled = true

[modules.parser.handlers.typescript]
enabled = true

[modules.parser.handlers.html]
enabled = true

[modules.parser.handlers.css]
enabled = true

[modules.rag]
enabled = false
extras = ["rag"]
