# Default configuration bundled with raggd
# Generated workspaces copy this file alongside the rendered raggd.toml so you
# can inspect baseline settings and module toggles.

workspace = "~/.raggd"
log_level = "INFO"

[db]
manifest_modules_key = "modules"
manifest_db_module_key = "db"
manifest_backup_retention = 5
manifest_lock_timeout = 5.0
manifest_lock_poll_interval = 0.1
manifest_lock_suffix = ".lock"
manifest_backup_suffix = ".bak"
manifest_strict = true
manifest_backups_enabled = true

[modules]

[modules.source]
enabled = true
extras = []

[modules.file-monitoring]
enabled = false
extras = ["file-monitoring"]

[modules.local-embeddings]
enabled = false
extras = ["local-embeddings"]

[modules.mcp]
enabled = false
extras = ["mcp"]

[modules.mcp-rest]
enabled = false
extras = ["mcp-rest"]

[modules.parsers]
enabled = false
extras = ["parsers"]

[modules.rag]
enabled = false
extras = ["rag"]
